### ISSUE TITLE
Error since v4.26.0: (connection || this.sequelize).query(...).then is not a function

### ISSUE THREAD

**Issue by xdamman** [sequelize/sequelize#8840]
Hey happy new year! 🎉 😃 

I'm having this error with sequelize v4.26.0 and above but my code worked fine with the version just below (v4.25.2). What has changed that I missed?
Thank you!

```
Unhandled rejection TypeError: (connection || this.sequelize).query(...).then is not a function
    at ConnectionManager._refreshDynamicOIDs (/Users/xdamman/github/opencollective/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:190:7)
    at Promise.tap.tap.connection (/Users/xdamman/github/opencollective/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:161:21)
From previous event:
    at ConnectionManager.connect (/Users/xdamman/github/opencollective/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:154:8)
    at sequelize.runHooks.then (/Users/xdamman/github/opencollective/api/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:327:50)
    at runCallback (timers.js:781:20)
```

**Comment by sushantdhiman** [comment]
Can you submit a test case so it can be fixed?

**Comment by raphodn** [comment]
hi @xdamman did you manage to fix the issue ?
I'm trying to upgrade Sequelize from v3.30.3 to v4.30.2 and I'm facing the same issue. I use `sequelize.query('...SQL...')` a couple of times in my code

**Comment by sushantdhiman** [comment]
What is your postgres database version and `pg` version, any way to reproduce this issue?

**Comment by raphodn** [comment]
I have Postgres 9.6, and `npm view pg version` returns 7.4.1
I commented all the times where I use `sequelize.query()` but I still get the error.
Sadly I'm going to have a very hard time to make a reproducible version of the code, the app is pretty big..

My full stack trace is:
```
Unhandled rejection TypeError: (connection || this.sequelize).query(...).then is not a function
    at ConnectionManager._refreshDynamicOIDs (/Users/raphael/my-big-app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:190:7)
    at Promise.tap.tap.connection (/Users/raphael/my-big-app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:161:21)
    at PassThroughHandlerContext.finallyHandler (/Users/raphael/my-big-app/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/Users/raphael/my-big-app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/raphael/my-big-app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/raphael/my-big-app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/raphael/my-big-app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/raphael/my-big-app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/raphael/my-big-app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/raphael/my-big-app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/raphael/my-big-app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by sushantdhiman** [comment]
`pg@7.x` is not supported, can you try with `pg@6` and see if that fix this issue

**Comment by raphodn** [comment]
My bad, I had a look at my `package-lock.json` and did a `npm list pg` instead, it returns `4.5.6`. sorry about that

**Comment by sushantdhiman** [comment]
So it seems `pg@4` doesn't support `connection.query` as promise, Can you try with `pg@6` and see if that resolves this issue

**Comment by eklenin** [comment]
I have this issue with one project, `sequelize@3` does not let upgrade `pg` - too many changes in code is required to upgrade sequelize itself.
And `pg@6` is blocking from upgrading Node to v14.

It looks like the only breaking changes between `pg@6` and latest `pg >8.0.3` versions is this hange in query mehtod of Client api - documented here https://node-postgres.com/guides/upgrading#clientqueryon

Previous api sources: https://github.com/brianc/node-postgres/blob/v6.4.2/lib/client.js#LL355C13-L355C13

New api sources: https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/client.js#L501

## Fix

I've end up with hack, that's tweaks `Client` query method to behave in the old way without changing the functionality:

Hack code:

```js
// app/pg8-original-query-tweak.js
const { Query, Client } = require('pg');

const originalQuery = Client.prototype.query;

Client.prototype.query = function (...args) {
    const [inputQuery, values, ...restArgs] = args;

    // Make query instance of Submittable to emulate old behaviour
    let query = inputQuery;
    if (typeof inputQuery === 'string') {
        query = new Query(inputQuery, values);
    }

    return originalQuery.apply(this, [query, ...restArgs]); // Call the original query method
};

// Just to avoid require issues
module.exports = { Client };
```

App entrypoint:
```js
// app/server.js
require('./pg8-original-query-tweak');
// ... rest of app code
```

If this fix will be approved deployed and tested in prod, i'll let you know how it ends.
Locally everything seems to work.

And if you find it usefull and succesfully apply this in your work, please return with some feedback, it would be nice to hear
