### PR TITLE
fix(query-generator): correctly treat projection inversion in include default scope

### LINKED ISSUE #10399: TypeError: include.attributes.map is not a function
## What are you doing?

https://gist.github.com/aaronfulkerson/ea67f28369c13fbb4267e365b0f879fa

## What do you expect to happen?
In the Gist, my ticket model has a scope on it called 'show' which I use when I display individual tickets. It works fine except when I begin trying to get the users associated with a discussion.
I should be able to get the users of a discussion since I have created a belongsToMany association through UserDiscussions. The code in the Gist works fine on version 4.42.0!

## What is actually happening?
 I can create a ticket and associate users to a discussion but when I try to retrieve them along with a post, I get the error in the title: "TypeError: include.attributes.map is not a function"

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ 11
__Sequelize version:__ 5.0.0-beta.16
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

### PR DESCRIPTION
**Pull request by SimonSchick**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` or `npm run test-DIALECT` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [x] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [x] Did you follow the commit message conventions explained in [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md)?

### Description of change

Fixes #10399

@u9r52sld please look at this too as your change caused this issue.

### CODE REVIEW

**Comment by eseliger** [comment]
@SimonSchick  would you want to wait for @u9r52sld to respond?

**Comment by SimonSchick** [comment]
@eseliger I'd prioritise rolling out this fix over waiting for a response.
