### ISSUE TITLE
Property 'QueryTypes' does not exist on type 'Sequelize'.

### ISSUE THREAD

**Issue by pgraham** [sequelize/sequelize#11496]
## Issue Description

Type script error for raw queries after upgrade to v5 and removing @types/sequelize from dependencies.

### What are you doing?

```js
const { Sequelize } = require('sequelize');
const sequelize = new Sequelize(...);
sequelize.query('SELECT ...', { type: sequelize.QueryTypes.SELECT });
```

### What do you expect to happen?

Code should continue to compile.

### What is actually happening?

Typescript compiler error:
```
Property 'QueryTypes' does not exist on type 'Sequelize'.
```

### Environment

- Sequelize version: 5.19.2
- Node.js version: 12
- Operating System: MacOS
- If TypeScript related: TypeScript version: 3.6.3

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by SimonSchick** [comment]
This was rather deliberate, you should instead import the query types directly from the module since they are effectively an enum.

**Comment by pgraham** [comment]
Fair enough, but there is likely a lot of existing code that uses the documented code in my report. Maybe a documentation update is necessary?

Also, just because the type isn't declared, that object still exists at runtime which is going to encourage casting and the loss of type safety you'd generally expect from Typescript.

**Comment by papb** [comment]
> Fair enough, but there is likely a lot of existing code that uses the documented code in my report. Maybe a documentation update is necessary?

Yup, I'm working on it (I'm working on a major docs rewrite actually)! Stay tuned.

> Also, just because the type isn't declared, that object still exists at runtime which is going to encourage casting and the loss of type safety you'd generally expect from Typescript.

I disagree, when people try to use TypeScript and get this error, like you did, they can fix it by casting (bad, as you said), or change it to the clean solution:

```js
const { Sequelize, QueryTypes } = require('sequelize');
const sequelize = new Sequelize(...);
sequelize.query('SELECT ...', { type: QueryTypes.SELECT });
```

I'll leave this open as a WIP docs issue

**Comment by maximinetto** [comment]
Hi, in versión 6.6.2 i have the same issue
`Model.findOne({
    attributes: [fn("MAX", col("idSeccion"))],
    where: {
      idSeccion,
    },
    raw: true,
  }).then((value) => {
    if (value === null) {
      return 0;
    }

    return value;
  });`
It's resolve if I change the types in model.d.ts for 
`export type ProjectionAlias = readonly string | Literal | Fn | Col;` But I don't know if it's a bad practice or broken something.

Sorry i'm a noob and my first languaje is spanish

**Comment by ephys** [comment]
The current documentation uses `const { QueryTypes } = require('sequelize');`, I'll close this now.
