### ISSUE TITLE
sequelize.col() not recognizing attribute alias

### ISSUE THREAD

**Issue by wangzc93** [sequelize/sequelize#10732]
## What are you doing?

I map the attribute `alias_a` to column `a` in database:
```js
class Test extends Model {}
Test.init({
    alias_a: { type: Sequelize.INTEGER, field: 'a' },
},{
    sequelize,
});
```
But when querying with `sequelize.col`, it can not recognize the alias I defined in Model.
```js
Test.findAll({
    attributes: [
        [sequelize.fn('SUM', sequelize.col('alias_a')), 'sum_a'],
    ],
});
```
I know `Test.sum('alias_a')` can recognize the alias defined in Model, but sometimes I need to use `findAll` to get other attributes at the same time.

## What do you expect to happen?
_{ sum_a: 123 }_

## What is actually happening?
_SequelizeDatabaseError: Unknown column 'alias_a' in 'field list'_

## What I have tried
I tried to solve this issue by adding a static method `col` to class `Model`:
```js
class _Model extends Model {
    static col(attribute) {
        const attrOptions = this.rawAttributes[attribute];
        const field = (attrOptions && attrOptions.field) || attribute;
        return this.sequelize.col(field);
        // above 3 lines are copied from Model.aggregate method
    }
}
```
Then I can do like:
```js
Test.findAll({
    attributes: [
        [sequelize.fn('SUM', Test.col('alias_a')), 'sum_a'],
    ],
});
```
which works fine.
Just wondering are there any better ways to handle this issue?

__Dialect:__ any
__Sequelize version:__ 5.2.13
__Tested with latest release:__ Yes

**Comment by TakanashiOuken** [comment]
Having the same issue here. Do you have a solution?

**Comment by wangzhilongh** [comment]
Having the same issue here. Do you have a solution?

**Comment by wangzc93** [comment]
@TakanashiOuken See my "What I have tried" section above.

**Comment by lokidarkeden** [comment]
I supose the code used to work around the issue should be moved into the Sequelize.col function, making the process transparent. I used some similar approach in the past with Sequelize 4.x, when updated to 5.x, the inner names seems to have changed and my software broke. Anyway, just leaving my +1 to this issue. By now, I will use the approuch in "What I have tried", thanks @wangzc93

**Comment by spimou** [comment]
@wangzc93 Can you give an example on how you use the `_Model ` class, because I am getting a `Test.col is not a function`
Sequelize version: 5.21.8 here

Thanks

**Comment by sreedharmb** [comment]
+1 Same issue. @wangzc93's "What I have tried" workaround is working for now but need to handle this at sequelize.col() itself.

**Comment by AlexandreL0pes** [comment]
+1 Same issue.

**Comment by ephys** [comment]
Still something that would be really nice to have

**Comment by ephys** [comment]
This was resolved by introducing `sql.attribute`: https://sequelize.org/docs/v7/querying/raw-queries/#sqlattribute
