### ISSUE TITLE
When Upgrade v5 to v6 Cannot find module './errors'

### ISSUE THREAD

**Issue by zainiazhr14** [sequelize/sequelize#13771]
I have issue when try upgrade v5 to v6 with error "Error: Cannot find module './errors'" and it show from "/node_modules/sequelize/lib/data-types"
Please Helpp
Thank You

**Comment by WikiRik** [comment]
To which version of v6 did you upgrade. v6.11.0?

**Comment by zainiazhr14** [comment]
i use sequelize^6.12.0-beta.2(latest)

**Comment by WikiRik** [comment]
@zainiazhr14 I would recommend upgrading to v6.11.0 first since v6.12.0-beta2 is an experimental beta version.
Nevertheless, @AllAwesome497 can you check this issue out?

**Comment by zainiazhr14** [comment]
okey thank you very much i hope can solve this problem

**Comment by Keimeno** [comment]
Could be due to https://github.com/sequelize/sequelize/pull/13710 will have to check it out. What node version are you using?

**Comment by zainiazhr14** [comment]
node v14.18.2

**Comment by AllAwesome497** [comment]
On node `v14.18.2` I'm able to `require` `sequelize@6.12.0-beta.2`. 

Can you make an example of this?  Are you using `import` or `require`?

Also worth noting: If you have any imports directly to `sequelize/lib` that won't be supported anymore since that is the source of sequelize which is in the process of being converted to TypeScript.

The transpiled code  should live in `sequelize/dist/lib/*` but I wouldn't recommend importing from there either; the `sequelize` index file exports everything from `data-types`.

**Comment by ephys** [comment]
This should have been resolved by https://github.com/sequelize/sequelize/pull/13795 which aliased `/lib` to `/dist/lib`. You still should not import anything from `/lib` yourself though.

Can you confirm that this is resolved @zainiazhr14?

**Comment by sezanzeb** [comment]
I'm having this issue with v6.13.0

Locally it works though, running node v14.17.6

In a docker container running node:12.16.1-buster it fails with this error:

```
Error: Cannot find module './errors'
Require stack:
- /builds/.../.../node_modules/sequelize/lib/data-types.js
- /builds/.../.../node_modules/sequelize/lib/utils.js
- /builds/.../.../node_modules/sequelize/lib/model.js
- /builds/.../.../src/database/Sequelize.js
```

**Comment by sezanzeb** [comment]
Can reproduce locally via `nvm install 12.16.1` and running my tests with this version.

**Comment by ephys** [comment]
That's because at the beginning of the typescript migration, files were moves from /lib to /lib/dist
It wasn't considered a breaking change at the time because files in /lib were considered internal. They still are but we've decided to freeze v6 and continue these changes in v7 to avoid further non-semver-major breaking changes.

We've since added a workaround using node's exports field, but it requires node >=12.20.0

You should however avoid importing anything from /lib

**Comment by hasan-hashtagged** [comment]
The issues are still there. I cloned the repo and tried running tests against mysql db. The test file test/integration/data-type.test.js still uses ```require('sequelize/lib/data-types')```. Is the migration still in progress? Also, in the package.json file, the entry points still contain lib.

**Comment by ephys** [comment]
If you cloned the sequelize repo, you need to run `yarn build` before running tests
`/lib` still exists, it's the build output of `/src` (https://github.com/sequelize/sequelize/pull/14068)

It's normal for the entrypoint to be in `/lib` as we need to expose the JS version of the codebase, not the TS one.

What this thread is about is that users should not try to import anything from `/lib` themselves directly. It's internal and prone to changes with no semver major bump. 
i.e. don't do `import DataTypes from 'sequelize/lib/data-types'`, do `import { DataTypes } from 'sequelize'`

It's normal for internal sequelize code to do it however

I'll close this issue as we've installed mitigation to not break v6 users that import from `/lib`, but we will remove this ability in v7 (exposing stable APIs instead)
