### ISSUE TITLE
TypeError: include.attributes.map is not a function

### ISSUE THREAD

**Issue by aaronfulkerson** [sequelize/sequelize#10399]
## What are you doing?

https://gist.github.com/aaronfulkerson/ea67f28369c13fbb4267e365b0f879fa

## What do you expect to happen?
In the Gist, my ticket model has a scope on it called 'show' which I use when I display individual tickets. It works fine except when I begin trying to get the users associated with a discussion.
I should be able to get the users of a discussion since I have created a belongsToMany association through UserDiscussions. The code in the Gist works fine on version 4.42.0!

## What is actually happening?
 I can create a ticket and associate users to a discussion but when I try to retrieve them along with a post, I get the error in the title: "TypeError: include.attributes.map is not a function"

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ 11
__Sequelize version:__ 5.0.0-beta.16
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by SimonSchick** [comment]
Could you also post the stacktrace for good measure?

**Comment by contra** [comment]
Can confirm this is happening on the latest anywhere a scope contains `excludes` and `includes` keys instead of a plain array.

**Comment by aaronfulkerson** [comment]
Yeah, thanks to @contra I figured out what's going on. On my User model the default scope excludes the password digest and if I remove that it "works" fine.

**Comment by contra** [comment]
@aaronfulkerson You can use the internal function to pre-prepare the attributes as a temporary workaround.

```js
const model = Model.scope(scope)
model._expandAttributes(query) // make the attribute option valid
```

(`_expandAttributes` mutates `query.attributes`)

**Comment by aaronfulkerson** [comment]
@contra fantastic tip. Thank you very much.

**Comment by yoann217** [comment]
same probleme here on 5.1.0 with mysql

**Comment by rlindgren** [comment]
Same issue as @yoann217 with 5.1.0 where `attributes.exclude` is defined on the `defaultScope`

**Comment by weyert** [comment]
Yes, I have the same issue with Postgres

**Comment by ALiangLiang** [comment]
Same issue on MySQL.....

**Comment by SimonSchick** [comment]
Can one of you please post a full repro, I tried to repro this locally just now but could not cause that error.

**Comment by SimonSchick** [comment]
fyi @sushantdhiman #9735 broke this (verified by bisect).

**Comment by SimonSchick** [comment]
Minimal repro:

```
'use strict';

const { Sequelize, Model, DataTypes } = require('./');

const sequelize = new Sequelize('mysql://root:bepis@localhost/test123');

class User extends Model {}
User.init({
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true
  },
  login: DataTypes.STRING
}, {
  timestamps: false,
  sequelize
});

class Ticket extends Model {}
Ticket.init({
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
  },

  name: {
    type: DataTypes.STRING,
  }
}, {
  defaultScope: {
    attributes: {
      exclude: ['name']
    }
  },
  sequelize,
});

User.hasMany(Ticket);

(async () => {
  await sequelize.sync();
  await User.findOne({
    include: [Ticket],
  })
})();
```

**Comment by ALiangLiang** [comment]
@SimonSchick
Yes. I have this issue when I use `defaultScope.attributes.exclude` too.

**Comment by adamasantares** [comment]
This problem still exists om Sequelize 6.2

```
        let results = await sequelize.query(sql, {
            replacements: {
                userid: this.id
            },
            model: User,
            attributes: {  // DOESN'T work as an object
                exclude: [
                    'password',
                    'created_at',
                    'updated_at'
                ]
            }
        });
```
