### ISSUE TITLE
Allow different additional attributes in the join table for associations when updating them through the special methods/mixins

### ISSUE THREAD

**Issue by garretaserra** [sequelize/sequelize#13730]
## Issue Creation Checklist
[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Feature Description
I would like the ability to set or add the associations between models when using special methods/mixin with different extra attributes so that each association can have its own extra attrribute values.

### Is your feature request related to a problem? Please describe.

Currently when using foo.setBar() or foo.addBar() we have the ability to add extra attributes to the bar<->foo relationship table with the options.through argument. The problem is that even though with these functions we can update more than one relationship, it is only possible to define a signle set of values for the extra attributes.

### Describe the solution you'd like

The easiest non breaking change would be to allow the options.through argument to accept an array of objects of the same length of the array in the first argument.
Instead of applying the same extra attributes to every query use the respective one.

```js
const Baz = sequelize.define('baz', {
  extraColumn: DataTypes.BOOLEAN
});
Foo.belongsToMany(Bar, { through: Baz })
Bar.belongsToMany(Foo, { through: Baz })

const foo = await Foo.create({ name: 'the-foo' });
const bar1 = await Bar.create({ name: 'some-bar' });
const bar2 = await Bar.create({ name: 'another-bar' });

// Currently this will set both relationships with the column "anotherExtraColumn" as true
await foo.addBars([bar1, bar2], {through: {extraColumn: true}});

// New functionality would allow setting different values for each association
await foo.addBars([bar1, bar2], {through: [{extraColumn: true}, {extraColumn: false}]});
```
With the proposed functionality the foo<->bar1 relationship can have extraColumn set to true and the foo<->bar2 relationship can have the extraColumn set to false.

Regarding backwards compatibility I would check if the through option has an object or an array. If it has an object I would keep the current functionality. If it has an array I would apply the proposed new functionality.

The problem that comes with this implementation is how to handle when there is a mismatch between the length of the array in the first argument of the function and the array in the through option. In that case I would suggest throwing an error with an explanation that the arrays length must match.

### Why should this be in Sequelize

This new feature would allow relationships that have non unique extra attributes to be easily updated in bulk.

### Describe alternatives/workarounds you've considered

There is a way to overcome this which is to first delete all the associations and then use the bar.add() for each association with the through option. This is obviously not great, error prone, and not scalable.

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by garretaserra** [comment]
Waiting for review

**Comment by WikiRik** [comment]
I think the idea is good, you thought about backward compatibility so that is nice. I think that it's best to throw an error if the length of the arrays is not the same.
If you have any questions about implementing this, feel free to make a comment here or to send us a message on Slack (links are in the README). Looking forward to the PR!

**Comment by fogolin** [comment]
Any news on this? Just came across the same problem.

**Comment by garretaserra** [comment]
Hi, at the time when I opened the issue I took a look at the source code and although I had some ideas of how to do it I wasn't knowledgeable enough to work on this. I might be now though so if I have time I might look into it but do not expect anything out of me and feel free to look into it.

**Comment by panda-p1** [comment]
Is there news?

**Comment by garretaserra** [comment]
I haven't succeded in setting up sequelize for development reaching out on slack for help at the moment.

**Comment by garretaserra** [comment]
I have reached out at slack but after not receiving any response will post my issues here just in case anyone can help me:

I'm trying to contribute a feature to sequelize but can't seam to find how to set the project correctly.
I'm following CONTRIBUTING.md file in the github repo.
Have cloned the repository and executed yarn to install dependencies.
Working on Windows with VScode, node 18.15
Next when executing
`yarn test-sqlite`
it doesn't find the script. I have checked in package.json and it isn't there.
I noticed that it was inside the core package, executed the command there it opens the build-packages.mjs file in the IDE. It then fails with over 1.5K typescript errors.
After looking at the test files with vscode it seams that some are for TODOs or other TS stuff but some of them are:
Cannot find module '@sequelize/core.....
Not sure how could I proceed or if there are other instructions to setup for development of sequelize.

**Comment by WikiRik** [comment]
@garretaserra I think the CONTRIBUTING.md file is outdated now that we are using a monorepo setup. What you need to do is the following; in the root folder execute `yarn && yarn build` to install the dependencies and build the packages. Then you can either cd into `packages/core` and execute `yarn test-sqlite` in there or stay in the root folder and do `yarn workspace @sequelize/core test-sqlite`
If that does not work, feel free to send me a DM on Slack with the errors you are getting

**Comment by garretaserra** [comment]
waiting on sequelize/sequelize#16101 and sequelize/website#494
