### PR TITLE
feat: update TypeScript support to 5.8 - 6.0

### PR DESCRIPTION
**Pull request by WikiRik**
## Pull Request Checklist

- [x] Have you added new tests to prevent regressions?
- [ ] If a documentation update is necessary, have you opened a PR to [the documentation repository](https://github.com/sequelize/website/)?
- [x] Did you update the typescript typings accordingly (if applicable)?
- [x] Does the description below contain a link to an existing issue or a description of the issue you are solving?
- [x] Does the name of your PR follow [our conventions](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#6-commit-your-modifications)?

## Description of Changes

**Top of the stack, stacked on #18331.**

Moves the supported TypeScript range up from `5.5`–`5.8` to **`5.8`, `5.9` and `6.0`**, and builds on `6.0.2`.

### ConstraintChecking had to be restructured

TypeScript 6.0 rejects `ConstraintChecking.DEFERRED` and `IMMEDIATE` as they were written:

```
src/deferrable.ts(67,19): error TS4094: Property '#constraints' of exported
anonymous class type may not be private or protected.
```

Both were class expressions passed straight to `classToInvokable` inside a static property initializer, so the *type* they produce has no name to refer to, and a private field cannot be described in the emitted declarations without one. They now have named declarations outside the class body, with the static accessors kept as the documented entry points — which preserves both the class names and the descriptions the generated docs point at.

> One observable side effect: `DEFERRED` and `IMMEDIATE` become static accessors rather than enumerable data properties, so they no longer appear in `Object.keys(ConstraintChecking)` or a spread of it. Both are still reached the same way.

`cls.test.ts` also gains an explicit `declare id: CreationOptional<number>`, which 6.0 needs to infer the model's creation attributes.

This is the one non-mechanical change in the PR, so it is covered by new unit tests in `packages/core/test/unit/deferrable.test.ts`: accessor identity, name preservation, construction with and without `new`, frozen constraints, and `isEqual` (including that `DEFERRED` and `IMMEDIATE` are never equal to each other).

### Everything else is mechanical

The `@ts-ignore` comments that newer compilers no longer need are dropped, and the two in the data types test become `@ts-expect-error` — which is what their own comments said they were waiting to be:

```ts
// eslint-disable-next-line @typescript-eslint/prefer-ts-expect-error -- error only appears in TS 5.5+
// @ts-ignore -- intentionally testing invalid input
```

### Ordering

TypeDoc had to reach 0.28 first (#18331); 0.27 refuses to run on TypeScript 6.0 and `docs` is a required CI job.

## Verification

`yarn build`, `yarn test-unit` (2220 passing), `yarn test-typings` across all 13 projects, and `yarn docs` with no warnings — all on TypeScript 6.0.2.

---

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01EgPPfqYYk6PFGbanp5mAFh

## Summary by CodeRabbit

* **Compatibility**
  * Added TypeScript 5.9 and 6.0 to typing validation alongside TypeScript 5.8.
  * Updated the development toolchain to TypeScript 6.0.2.

* **Bug Fixes**
  * Improved consistency and reliability of constraint-checking behavior while preserving existing functionality.

* **Tests**
  * Added coverage for deferred and immediate constraint-checking behavior, including equality, immutability, and construction scenarios.

### CODE REVIEW

File: packages/core/src/deferrable.ts [hunk 1]
```diff
@@ -64,51 +64,58 @@ export class ConstraintChecking {
...
+    return ConstraintCheckingImmediate;
+  }
+}
+
+class DEFERRED extends ConstraintChecking {
+  readonly #constraints: readonly string[];
+
+  /**
+   * @param constraints An array of constraint names. Will defer all constraints by default.
+   */
```
Comment (WikiRik) [inline packages/core/src/deferrable.ts]:
```suggestion
```

File: packages/core/src/deferrable.ts [hunk 2]
```diff
@@ -64,51 +64,58 @@ export class ConstraintChecking {
...
+    return this.#constraints;
+  }
 }
+
+class IMMEDIATE extends ConstraintChecking {
+  readonly #constraints: readonly string[];
+
+  /**
+   * @param constraints An array of constraint names. Will defer all constraints by default.
+   */
```
Comment (WikiRik) [inline packages/core/src/deferrable.ts]:
```suggestion
```

**Review by SippieCup — APPROVED** [review]
LGTM
