### PR TITLE
fix(typings): add missing nested to Includeable

### PR DESCRIPTION
**Pull request by vanthome**
Typings were missing previously.

### Description of change

Add `nested` to typings `Includeable`.

### CODE REVIEW

**Comment by papb** [comment]
LGTM

**Comment by sushantdhiman** [comment]
This needs a typing test similar to https://github.com/sequelize/sequelize/blob/5860ef5f378bbea8e53c4ec58ec3a6a94fea3a1a/types/test/include.ts#L27

**Comment by papb** [comment]
@vanthome it seems you pushed a new commit by accident, am I right?

**Comment by vanthome** [comment]
OMG, I did not know that pushes are still synchronized here because I did not crate another PR. I guess when we close this PR this will no longer be the case, or?
Btw. I will prepare this as a fresh PR hopefully soon.

**Comment by papb** [comment]
image

Whenever you push to the `missing_typing` branch, this PR will be updated (unless it was already merged, of course). I am not sure what would happen if the PR is closed (not merged), but I'd guess it would still be updated, except that probably the automatic checks would not run...

If you want to work on multiple PRs at the same time you just have to create one branch for each one and pay attention where you are commiting :)

**Comment by papb** [comment]
> This needs a typing test similar to
> 
> https://github.com/sequelize/sequelize/blob/5860ef5f378bbea8e53c4ec58ec3a6a94fea3a1a/types/test/include.ts#L27

By the way can you address this comment so we can merge this PR?

**Comment by vanthome** [comment]
Ok, I was accidental in a branch. I reverted and rebased. Btw. why is this not merged yet? Is there something missing?

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/pull/11354#issuecomment-525577167

**Comment by papb** [comment]
I think you pushed by mistake again : grimacing:

By the way please address the comment so we can merge this

**Comment by papb** [comment]
@vanthome If you need help to create the test let me know

**Comment by vanthome** [comment]
NP, added the test, now please merge it.

**Comment by vanthome** [comment]
Just one question. I'm working on another PR but now with the 6.0 master the existing PG tests are failing for me:

```
  1) [POSTGRES] Model
       schemas
         regressions
           should be able to sync model with schema:
     TypeError: s.replace is not a function
      at Object.removeTicks (lib/utils.js:354:12)
      at Object.quoteIdentifier (lib/dialects/abstract/query-generator/helpers/quote.js:50:35)
      at PostgresQueryGenerator.quoteIdentifier (lib/dialects/abstract/query-generator.js:859:24)
      at PostgresQueryGenerator.quoteTable (lib/dialects/abstract/query-generator.js:906:23)
      at PostgresQueryGenerator.addIndexQuery (lib/dialects/abstract/query-generator.js:543:24)
      at QueryInterface.addIndex (lib/query-interface.js:658:37)
      at /P/BMS-LSA/sequelize/lib/model.js:1358:67
  From previous event:
      at /P/BMS-LSA/sequelize/lib/model.js:1358:24
  From previous event:
      at Function.sync (lib/model.js:1345:8)
      at Context.<anonymous> (test/integration/model/schema.test.js:543:23)
      at processImmediate (internal/timers.js:439:21)
```

Can you confirm that they are not functioning right now?

**Comment by papb** [comment]
About the tests you mentioned, that's odd, latest commit on master has a green checkmark... I suggest you proceed with your PR, if you think the error is unrelated just ignore it for now, we shall look into it once you open the PR :)
