### ISSUE TITLE
types/utils/immutability.d.ts class returns compilation error when I upgrade to version 7 alpha 

### ISSUE THREAD

**Issue by HMhamedminaee** [sequelize/sequelize#15975]
Hi 
after upgrading to v7 alpha I see the following error and my project cannot even compile 
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/97239026/235279637-9e3ab323-5f15-4a6f-b93e-5dcf4442e81f.png">

is there any missing dependency in v7 alpha version?

**Comment by WikiRik** [comment]
I believe you are using an outdated version of Node, you need to use 14.17.0 or higher. See also https://github.com/sequelize/sequelize/blob/main/packages/core/package.json#L40

**Comment by HMhamedminaee** [comment]
Actually I am using v16.18.1 
@WikiRik

**Comment by HMhamedminaee** [comment]
As soon as I starts importing anything like 
`import {DataTypes} from "@sequelize/core";`
it starts complaining about 
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/97239026/235318990-b11c3409-4af7-4e46-a493-51382d33d262.png">
though my node is 
`node --version
v16.18.1`

and 
`npm --v       
8.19.2`

**Comment by ephys** [comment]
Which version of `@types/node` are you using?

**Comment by HMhamedminaee** [comment]
Thanks @ephys you pointed me to the right direction 
after bumping up my @types/node it worked :)
