### ISSUE TITLE
v6.2.2+ introduces breaking changes over v6.2.0 for TypeScript Model.init

### ISSUE THREAD

**Issue by j-m** [sequelize/sequelize#12452]
### What are you doing?

(SSCCE example repo uses JavaScript not TypeScript, maybe consider a separate issue template for TS)

Defining a model through `Model.init` and ommitting implicit fields like so:

```ts
import { Model, DataTypes } from 'sequelize'
import { database } from '../connection'

export interface NoteAttributes extends NoteCreationAttributes {
  id: number
  createdAt: Date
  updatedAt: Date
}

export interface NoteCreationAttributes {
  UserId: number
  content: string
}

export class Note extends Model<NoteAttributes, NoteCreationAttributes>
  implements NoteAttributes {
  public id!: number
  public UserId!: number
  public content!: string

  public readonly createdAt!: Date
  public readonly updatedAt!: Date
}

Note.init(
  {
    UserId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    content: {
      type: new DataTypes.TEXT('long'),
      allowNull: false,
    },
  },
  {
    sequelize: database,
    tableName: 'notes',
  }
)
```
Complains that I am missing, id, createdAt, and updatedAt fields
```
/models/Note.ts:19:3 - error TS2345: Argument of type '{ UserId: { type: DataTypes.IntegerDataTypeConstructor; allowNull: false; }; content: { type: DataTypes.TextDataType; allowNull: false; }; }' is not assignable to parameter of type 'ModelAttributes<Note, NoteAttributes>'.
      Type '{ UserId: { type: IntegerDataTypeConstructor; allowNull: false; }; content: { type: TextDataType; allowNull: false; }; }' is missing the following properties from type 'ModelAttributes<Note, NoteAttributes>': id, createdAt, updatedAt

     19   {
          ~
     20     UserId: {
        ~~~~~~~~~~~~~
    ...
     27     },
        ~~~~~~
     28   },
```

### What do you expect to happen?

The above code compiles in v6.2.0 and v6.2.1

### What is actually happening?

The above code does not compile in v6.2.2+ despite only a patch version increment.

### Environment

- Sequelize version: See above
- Node.js version: 14
- Operating System: Win10
- If TypeScript related: TypeScript version: ^3.9.5

### How does this problem relate to dialects?

I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by Keimeno** [comment]
A quick fix should be to use 
```ts
interface NoteCreationAttributes extends Optional<NoteAttributes, 'id'> {}
```

Also your NoteAttributes shouldn't implement the `createdAt` and `updatedAt` attributes.

But I'll take a look into that.

**Comment by j-m** [comment]
> Also your NoteAttributes shouldn't implement the createdAt and updatedAt attributes.

Ahhh, I thought it was supposed to contain all attributes of the Model, seems odd to have id if its not supposed to have other automatic values like the dates.
