### ISSUE TITLE
Error: Cannot find module 'cls-bluebird' / Cannot find module './utils/classToInvokable'

### ISSUE THREAD

**Issue by DanielOverdevest** [sequelize/sequelize#13134]
## Issue Description
After upgrade from v5 to v6 (6.6.1)

### What are you doing?
Upgraded from v5 to v6. Server started. Upon requesting data using .findOne() I got this cannot find module.
First I got the `cls-bluebird` is not found. After adding this dependency I got Cannot find module './utils/classToInvokable'.

Note: I can't reproduce it on my laptop (MacBook) but had issues running it on Azure WebApp Services.

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/153 

### What do you expect to happen?

Dependencies are found and data has been returned upon simple .findOne()

### What is actually happening?

First error
`Error: Cannot find module 'cls-bluebird'`

```
Require stack:
- D:\home\site\wwwroot\node_modules\sequelize\lib\sequelize.js
- D:\home\site\wwwroot\node_modules\sequelize\index.js
- D:\home\site\wwwroot\models\index.js
- D:\home\site\wwwroot\server.js
- D:\Program Files (x86)\iisnode\interceptor.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sequelize\lib\sequelize.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

After resolving cls-bluebird (`npm install cls-bluebird --save`) dependency I got this error.
`Error: Cannot find module './utils/classToInvokable'`

```
Error: Cannot find module './utils/classToInvokable'
Require stack:
- D:\home\site\wwwroot\node_modules\sequelize\lib\data-types.js
- D:\home\site\wwwroot\node_modules\sequelize\lib\utils.js
- D:\home\site\wwwroot\node_modules\sequelize\lib\sequelize.js
- D:\home\site\wwwroot\node_modules\sequelize\index.js
- D:\home\site\wwwroot\models\index.js
- D:\home\site\wwwroot\server.js
- D:\Program Files (x86)\iisnode\interceptor.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sequelize\lib\data-types.js:12:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sequelize\lib\utils.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

```

### Environment

- Sequelize version: 6.6.1 
- Node.js version: 14.15.1 
- Operating System: Windows / Azure App Services

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
I don't use CLS so I'm not certain what the issue is but noted in the upgrade documentation ( https://sequelize.org/master/manual/upgrade-to-v6.html ) is that you should "now" use a package named cls-hooked. I take this to mean the package you're using, cls-bluebird, is deprecated.

**Comment by DanielOverdevest** [comment]
Thanks for leaving a comment @Spekpannenkoek. For now I reverted the upgrade and will investigate if cls-hooked is a mandatory dependency to run it on Windows / Azure WebApps with Node 14.15.1.
I also don't use cls (what I get from it that it's being used for transactions).
I will experiment in a couple of days.

**Comment by papb** [comment]
This is very likely a cache issue with something.

Can you please run `node -p "require('D:\\home\\site\\wwwroot\\node_modules\\sequelize\\package.json').version"` and post the result here?
