### ISSUE TITLE
Error: Cannot find module 'pg-native'

### ISSUE THREAD

**Issue by tornillo** [sequelize/sequelize#3781]
Exception occurs when trying to add two (or more) equal values in a unique field using findOrCreate.

Test code:

``` javascript
var arr = [0, 1];

var User = sequelize.define('User', {
    login: {
        type: Sequelize.STRING,
        unique: true
    }
});

User.sync({ force: true })
.then(function () {
    sequelize.transaction()
    .then(function (tx) {
        return Promise.map(arr, function () {
            return User.findOrCreate({
                where: {
                    login: 'test'
                },
                transaction: tx
            });
        })
        .then(function () {
            tx.commit();
        });
    });
});
```

SQL log:

``` SQL
Executing (default): DROP TABLE IF EXISTS "Users" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "Users" ("id"   SERIAL , "login" VARCHAR(255) UNIQUE, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' and t.relname = 'Users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (6a28eaa0-9716-4db0-be66-967f8ec12058): START TRANSACTION;
Executing (6a28eaa0-9716-4db0-be66-967f8ec12058): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (6a28eaa0-9716-4db0-be66-967f8ec12058): SET autocommit = 1;
Executing (6a28eaa0-9716-4db0-be66-967f8ec12058): SAVEPOINT "6a28eaa0-9716-4db0-be66-967f8ec12058-savepoint-1";
Executing (6a28eaa0-9716-4db0-be66-967f8ec12058): SAVEPOINT "6a28eaa0-9716-4db0-be66-967f8ec12058-savepoint-2";
Executing (6a28eaa0-9716-4db0-be66-967f8ec12058): SELECT "id", "login" FROM "Users" AS "User" WHERE "User"."login" = 'test' LIMIT 1;
Executing (6a28eaa0-9716-4db0-be66-967f8ec12058): SELECT "id", "login" FROM "Users" AS "User" WHERE "User"."login" = 'test' LIMIT 1;
Executing (6a28eaa0-9716-4db0-be66-967f8ec12058): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "Users", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_66f952b0ec354cdbb8923433f3248e4a$ BEGIN INSERT INTO "Users" ("id","login") VALUES (DEFAULT,'test') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_66f952b0ec354cdbb8923433f3248e4a$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
Executing (6a28eaa0-9716-4db0-be66-967f8ec12058): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "Users", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_2abdfe30c027469dac0b5fe594fb4dda$ BEGIN INSERT INTO "Users" ("id","login") VALUES (DEFAULT,'test') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_2abdfe30c027469dac0b5fe594fb4dda$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
```

Error stack:

``` javascript
Unhandled rejection Error: Cannot find module 'pg-native'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/user/test/node_modules/pg/lib/native/index.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at null.<anonymous> (/home/user/test/node_modules/pg/lib/index.js:78:36)
    at /home/user/test/node_modules/lodash/index.js:3159:32
    at baseForOwn (/home/user/test/node_modules/lodash/index.js:2089:14)
    at baseClone (/home/user/test/node_modules/lodash/index.js:1799:39)
    at /home/user/test/node_modules/lodash/index.js:1800:23
From previous event:
    at Promise.catch (/home/user/test/node_modules/sequelize/lib/promise.js:21:17)
    at Object.<anonymous> (/home/user/test/node_modules/sequelize/lib/model.js:1199:15)
From previous event:
    at Promise.then (/home/user/test/node_modules/sequelize/lib/promise.js:21:17)
    at module.exports.Model.findOrCreate (/home/user/test/node_modules/sequelize/lib/model.js:1180:8)
    at /home/user/test/tests.js:30:16
From previous event:
    at /home/user/test/tests.js:29:18
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at Promise.then (/home/user/test/node_modules/sequelize/lib/promise.js:21:17)
    at Object.<anonymous> (/home/user/test/tests.js:26:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Note: without the transaction is the same error

**Comment by tornillo** [comment]
The error occurs when calling optClone->lodash.cloneDeep from findOne and other similar methods.
The PG-module has a property 'native', which is a getter:

```javascript
module.exports.__defineGetter__("native", function() {
  delete module.exports.native;
  module.exports.native = new PG(require('./native'));
  return module.exports.native;
});
```
During cloning this getter is called and throwing error.


Workarounds:

1: Before Sequelize initialization in application we can remove stupid getter:
```javascript
require('pg');
delete pg.native;
```
**It should be documented.**


2: Delete getter when require PG in Sequelize connection-manager.js if config.native === false

3: Or we need to patch Units.clone for totally skipping property 'lib' cloning:
```diff
   cloneDeep: function(obj, fn) {
-    return lodash.cloneDeep(obj, function (elem) {
+    return lodash.cloneDeep(obj, function (elem, key) {
+      // Skip property 'lib' cloning (PG-native error workaround)
+      if (key === 'lib' && elem.hasOwnProperty('native')) {
+        return elem;
+      }
+
```

**Comment by janmeier** [comment]
Hmm, we've seen this problem before - optClone should be handling this problem already by not cloning transaction instances. Which version are you on?

**Comment by tornillo** [comment]
3.0.1 - latest
optClone clone all properties, pg.native is a getter.
Lodash cloneDeep iterates through all properties and gets a value of each -> getter called.

**Comment by tornillo** [comment]
...and only then transaction is skipped by checking:
```javascript
elem instanceof Transaction
```

**Comment by janmeier** [comment]
Hmm, it seems we are trying to clone a sequelize instance - which has a reference to the pg instance... weird..

**Comment by tornillo** [comment]
Oh, I missed the important thing:
It occurs only when findOne called an the end of findOrCreate
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1207

**Comment by zooofeex** [comment]
I am having the same issue

**Comment by tornillo** [comment]
Commit https://github.com/sequelize/sequelize/commit/4f9b502e410614edfe863a7a7c3006ae4a495d1a solved the problem.
Bug is not reproduced in version 3.1.1
Thank you!

**Comment by mickhansen** [comment]
Great :)

**Comment by stoiacs** [comment]
In 3.3.2 I had the same issue, workaround by tornillo solved (delete pg.native;).

**Comment by jbrawnjr** [comment]
Still encountering the optClone issue in 3.21.0.

**Comment by benjaminhon** [comment]
i still this error message occurring, but i have no idea why it came suddenly

**Comment by llonchj** [comment]
I'm experiencing same issue with 3.23.2 pg-native is required

**Comment by benjaminhon** [comment]
Im i realised that it was because i "new Sequelize()" in browserify. I removed it and it was ok.

**Comment by lrojas94** [comment]
may I ask @benjaminhon, what do you mean by removed the new Sequelize()? how do you init now?

**Comment by benjaminhon** [comment]
@lrojas94, i mean that i removed new Sequelize() from running on the client browser

**Comment by lrojas94** [comment]
I see.. I still have the issue though, and I'm not currently using it on the front-end at all... Did you manage to solve it @llonchj

**Comment by mz2** [comment]
Happening for me too with a many-to-many query of the following kind:

```
Version.findAll({
        include:[{
            model:Feed, 
            through:{
                attributes:[],
                where: {
                    feedIdentifier:appID
                }
            }
        }]
```

**Comment by TechnicalRhino** [comment]
same in version 4.37.6. Please reopen this bug.

**Comment by TwoAbove** [comment]
Can confirm, happening with v3.30.4

**Comment by nassan** [comment]
Confirming, happening with v4.29.2

**Comment by bludnic** [comment]
In my case, I fixed this way:

Changed from this:
`const sequelize = new Sequelize(process.env.DATABASE_URL, {
  native: true,
  ssl: true
})`

To this:
`const sequelize = new Sequelize(process.env.DATABASE_URL, {
  dialect: 'postgres',
  dialectOptions: {
    ssl: true
  }
})`

**Comment by dancrumb** [comment]
It should be noted that this is **not** purely a code issue. It depends on the environment.

I have the same code running in my local environment and my staging environment.

I see this issue **only** in my staging environment:

May be relevant:

staging - Aurora PostgreSQL -  PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit
local - PostgreSQL - PostgreSQL 10.2 (Debian 10.2-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit

**Comment by rzetterberg** [comment]
I have this problem in `4.37.10` too. 

I've found the exact line of code which triggers this error me, it's when I'm comparing a non-persistent Sequelize instance with a regular object using: `expect(myObject).to.deep.equal(mySequelizeInstance);`, where `expect` is defined as `const { expect } = require('chai');`.  

I guess the problem arises when Chai's `deep-eql` tries to inspect the native getter, or something similar. 
I get the same problem if I use lodash's `cloneDeep` on a Sequelize instance. 

So if you have code that inspects/clones a Sequelize instance you could be faced with this problem. For me the workaround was just to make sure that I got a plain object using the instance's method `toJSON` before doing any kind of inspection or cloning.

**Comment by pawelrychlik** [comment]
Interestingly, the same with sequelize `3.31.1`

**Comment by Jolg42** [comment]
Hi there!

It just happened to me as well but I found why ;-)

So first the `delete pg.native;` didn't work for me.

What happened in my case is that I have `winston` as a logger and I was doing something like `logger.debug({'fontFromDb': fontFromDb})`.
The logger tries to log everything and call this getter that shouldn't be called and 💥 

So make sure you don't have anything like a `clone` or a logger on an instance.
If you need to clone or log do it with a `raw: true` query that returns a JSON or turn the instance to JSON like this: `fontFromDb.toJSON()`

**Comment by Allain55** [comment]
I have this problem in 5.8.6 with NodeJS 12.2 and pg 7.11
When native is set to true, I get a "Cannot find module 'pg-native'" error message

**Comment by rusekr** [comment]
As I've seen pg-native wont compile with node 12 because of libpq wont compile https://github.com/brianc/node-libpq/pull/67

**Comment by cyrilchapon** [comment]
I'm facing this error inside my unit tests myself.

What happens is I'm testing "the return of a function" with sinon.js like so :

```
      sinon.assert.calledWith(
        underlyingFunction,
        sinon.match.instanceOf(MySequelizeModel)
          .and(sinon.match.has('theProp', expectedValue))
      )
```

When the test fails (passed sequelize instance doesn't have `"theProp"` equal to `expectedValue`); sinon complains and logs the sequelize instance (assuming `console.log`) to help me compare the expected value with actual value.

**Comment by abstructs** [comment]
I get this error when using chai "deep equals" on a model instance, using .toJSON() seemed to fix the issue

**Comment by papb** [comment]
From the looks of it, the workaround by tornillo should work for everyone.

> ```js
> const pg = require('pg');
> delete pg.native;
> ```

**Comment by rusekr** [comment]
> From the looks of it, the workaround by tornillo should work for everyone.
> 
> > ```js
> > const pg = require('pg');
> > delete pg.native;
> > ```

Fixed this by not installing pg-native module and sequelize config: 
```
var db = new Sequelize(..., {
  "dialect": "postgres",
  "native": false
});
```
Made some research about performance drawbacks and found nothing.

**Comment by cyrilchapon** [comment]
`delete pg.native` doesn't work for me, neither does the `native: false` inside the options

**Comment by papb** [comment]
@cyrilchapon Are you sure you are applying [this](https://github.com/sequelize/sequelize/issues/3781#issuecomment-522198459) before anything else runs, i.e., in the first line of your entry point?

**Comment by cyrilchapon** [comment]
@papb pretty sure, but not confident.
This is in a unit-test environement.

I'll double check

**Comment by cyrilchapon** [comment]
Just a word. This issue is 4,5 years ago.
I think one could expect a little more than an obscure an not-always-working workaround to fix an issue on a ORM, IMHO. Just to say

**Comment by cyrilchapon** [comment]
Related : https://github.com/sequelize/sequelize/issues/3101

**Comment by papb** [comment]
@cyrilchapon I agree! Hence this issue is still open.

**Comment by AlariCode** [comment]
So after reading `pg` module code, I found that problem with bundling is in index.js file:
```
if (typeof process.env.NODE_PG_FORCE_NATIVE !== 'undefined') {
  module.exports = new PG(require('./native'))
} else {
  module.exports = new PG(Client)

  // lazy require native module...the native module may not have installed
  module.exports.__defineGetter__('native', function () {
    delete module.exports.native
    var native = null
    try {
      native = new PG(require('./native'))
    } catch (err) {
      if (err.code !== 'MODULE_NOT_FOUND') {
        throw err
      }
      /* eslint-disable no-console */
      console.error(err.message)
      /* eslint-enable no-console */
    }
    module.exports.native = native
    return native
  })
```

It requires `./native` file which is depending on `pg-native`. So to pack it with webpack we need to ignore this import. To do it just use `webpack.IgnorePlugin`:

```
new webpack.IgnorePlugin(/.\/native/),
```

After this addition, everything works fine.

**Comment by 1valdis** [comment]
This bug blocks our production project. And it's 4.5 years old! `delete pg.native` doesn't work. Can this be fixed already?

**Comment by mickhansen** [comment]
@1valdis Do you have code that does deep clone on sequelize objects? Like a logger? The issue is usually not with Sequelize, if it with Sequelize, you're more than welcome to submit a PR to fix it.

**Comment by 1valdis** [comment]
@mickhansen we can't reproduce it reliably. It may or may not happen during one of requests. It may or may not happen after we update or downgrade packages. There's no situation which I can share and say "see, under this specific circumstances it triggers"...

**Comment by papb** [comment]
As AlariCode said:

> So after reading pg module code, I found that problem with bundling is in index.js file

This is a problem with pg, not Sequelize, and it's being worked on very recently: see [node-postgres#1894](https://github.com/brianc/node-postgres/issues/1894) and [node-postgres#1992](https://github.com/brianc/node-postgres/pull/1992).

**Comment by 1valdis** [comment]
@papb under pull request you referenced they turned this around on sequelize. Hmm...

**Comment by papb** [comment]
@1valdis Hmmm, thanks for pinging, I will look into it later

**Comment by Volshebniqq** [comment]
For me, this error occurred when I tried to put Sequelize instance inside of a Winston logger.
```
logger.info('getSegmentData', { lastAttempt, previousAttempt });
```
Fix:
```
logger.info('getSegmentData', { 
    lastAttempt: lastAttempt ? lastAttempt.get({ plain: true }) : null,
    previousAttempt: previousAttempt ? previousAttempt.get({ plain: true }) : null
});
```

**Comment by papb** [comment]
@Volshebniqq thanks for posting, I've seen other people have similar problems with the winston logger, perhaps it is the one trying to deep clone stuff? Does anyone know if there is a related issue in the winston repository?

**Comment by jamiesoncj** [comment]
Just to add that I see this issue when trying to use the Winston logger too - for example as shown below. Haven't found an issue in the Winston repo yet.

```javascript

const transports = [
  new winston.transports.Console({
    json: true,
    colorize: true,
    handleExceptions: true,
    humanReadableUnhandledException: true,
  }),
];

const logger = winston.createLogger({
  level: 'debug',
  transports,
});

const sequelize = new Sequelize(config.databaseUrl, {
    logging: logger.debug.bind(logger),
    dialect: 'postgres',
    pool: {
      max: 5,
      min: 0,
      idle: 10000,
    },
    protocol: 'postgres',
    dialectOptions: {
      ssl: true,
    },
  });
```

**Comment by Eoksni** [comment]
@jamiesoncj I have the same issue as you and managed to workaround that by changing
```
    logging: logger.debug.bind(logger),
```

to
```
    logging: sql => logger.debug(sql),
```

No idea why it works, kinda makes no sense.

**Comment by jamiesoncj** [comment]
@Eoksni thank you for the tip - this works for me!

**Comment by vgeorge** [comment]
@Volshebniqq @papb @jamiesoncj @Eoksni Updating Winston to 3.2.1 fixed the problem for me.

**Comment by Eoksni** [comment]
Strange, I was having this error exactly with 3.2.1 winston.

**Comment by vgeorge** [comment]
@Eoksni My mistake, it's not working on version 3.2.1, the error still persists.

**Comment by cyrilchapon** [comment]
Please,
This issue is about sequelize models / transactions / whatever-objects messing up with whatever-logging strategy.

Maybe we should try not to polute this thread with workarounds for every-loggers-on-earth.
At the end of the day, `console.log(sequelizeModel)` just messes; the issue is about fixing that.

**Comment by counterbeing** [comment]
i just wanted to add here, that if you're using typescript, this works for me: `delete (pg as any).native;` and prevents errors.

**Comment by anistark** [comment]
This issue still persists. Anybody fixed it yet?

**Comment by papb** [comment]
@anistark I think you answered your own question :sweat_smile: hopefully it will be fixed as a side-effect of #11832

**Comment by anistark** [comment]
@papb 😅 What I meant was workarounds that might have worked for others successfully. 
Anyway, hope this gets merged soon. 🤞 Thanks for the swift response.

**Comment by 1valdis** [comment]
`pg@8` has been released, which contains a (hopefully) fix for this. Is it safe to upgrade though?...

**Comment by vladyslav-huba-lanars** [comment]
@papb I've been using pg@8 with Sequelize 5 for a month, having Winston as logger, and made a production app on the combo without ever encountering `cannot find module 'pg-native'`. Can you confirm that? In fact, nothing has broken in Sequelize 5 with pg@8 (and pg changelog suggested there are only very subtle breaking changes), so I think my upgrade was totally worth it.

**Comment by 1valdis** [comment]
@papb I've been using pg@8 with Sequelize 5 for a month, having Winston as logger, and made a production app on the combo without ever encountering `cannot find module 'pg-native'`. Can you confirm that? In fact, nothing has broken in Sequelize 5 with pg@8 (and pg changelog suggested there are only very subtle breaking changes), so I think my upgrade was totally worth it.

**Comment by superrandres** [comment]
![Screenshot_20200703_123050](https://user-images.githubusercontent.com/8306417/86489168-18774580-bd29-11ea-933c-084953dee657.png)
It happens to me, when making the query that is linked in the image. Basically I am relating two models of different schemas with different Sequelize instances. But when I make the query from line 13 (hasMany) there are no errors, the errors occur when executing the query from line 24 (belongsTo), both queries work but the last one generates the following:

`auto-rest_1  | Cannot find module 'pg-native'
auto-rest_1  | Require stack:
auto-rest_1  | - /app/general-persistence/node_modules/pg/lib/native/client.js
auto-rest_1  | - /app/general-persistence/node_modules/pg/lib/native/index.js
auto-rest_1  | - /app/general-persistence/node_modules/pg/lib/index.js
auto-rest_1  | - /app/general-persistence/node_modules/sequelize/lib/dialects/abstract/connection-manager.js
auto-rest_1  | - /app/general-persistence/node_modules/sequelize/lib/dialects/postgres/connection-manager.js
auto-rest_1  | - /app/general-persistence/node_modules/sequelize/lib/dialects/postgres/index.js
auto-rest_1  | - /app/general-persistence/node_modules/sequelize/lib/sequelize.js
auto-rest_1  | - /app/general-persistence/node_modules/sequelize/index.js
auto-rest_1  | - /app/general-persistence/index.js
auto-rest_1  | - /app/logic/front/auth/clientes.js
auto-rest_1  | - /app/auto-rest/cookiesManagment.js
auto-rest_1  | - /app/auto-rest/index.js
`
I also have an error that I have not yet checked in MongoDb when storing hook afterFind information that is not given in other queries.
`Error: cyclic dependency detected`

**Comment by 1valdis** [comment]
@superrandres do you use `pg@8.0.0` or above?

**Comment by superrandres** [comment]
Hello @1valdis thanks for answering. I indicate the versions that I am using:
    "pg": "^7.14.0",
    "pg-hstore": "^2.3.3",
    "sequelize": "^5.22.3"
The MongoDB error has nothing to do with this.

**Comment by 1valdis** [comment]
@superrandres you have `pg@7.14.0`. Try using `pg@8` or above (`npm i -s pg@8`) and see if the error is still there.

**Comment by superrandres** [comment]
@1valdis  This solved the problem, thank you very much.

**Comment by jeromeSH26** [comment]
Hi,
still got this error by just testing the connection (using `native=true`) in the connection options. Have to turn it to false.

The workaround to delete the pg.native property is failing as this is a readonly property (in typescript)
```

"pg": "^8.3.3",
"pg-hstore": "^2.3.3",
"sequelize": "^6.3.5",
```

```
const dbConnection: Sequelize = new Sequelize(
		DB_PARAMS.DB_DATABASE,
		DB_PARAMS.DB_USER,
		DB_PARAMS.DB_PWD,
		{
			host: DB_PARAMS.DB_HOST,
			dialect: DB_PARAMS.DB_DIALECT.toLowerCase() as Dialect,
			logging: DB_PARAMS.DB_LOG,
			minifyAliases: true,
			native: true,
			pool: {
				min: DB_PARAMS.DB_MINPOOL,
				max: DB_PARAMS.DB_MAXPOOL,
			},
			port: DB_PARAMS.DB_PORT,
			quoteIdentifiers: true,
			typeValidation: true,
		}
	);
```
![image](https://user-images.githubusercontent.com/51024915/94336999-6da0bb80-ffe7-11ea-9334-7890ad53d4a9.png)

**Comment by sshaginyan** [comment]
Same issue as @jeromeSH26

**Comment by soryy708** [comment]
If the failure happens at build time (e.g. when running webpack), and you don't want to use `pg-native`, you can add it to webpack's `externals` s.t. it doesn't complain if it can't find the package.

**Comment by ps2goat** [comment]
@jeromeSH26 @sshaginyan 

This should work in typescript, though I haven't tested.

```js
delete (<any>pg).native;
```

**Comment by ps2goat** [comment]
I have confirmed that the line above works in Typescript. I had similar issues with TypeORM, not Sequelize. It appears to be an issue with the `pg` npm package, which is odd. I've seen it work on other machines...

**Comment by papb** [comment]
[Since version 8, the `.native` getter is no longer enumerable](https://github.com/brianc/node-postgres/issues/1894#issuecomment-657081945), therefore this problem can be avoided by upgrading to `pg` 8. For this reason I will close this issue now. If anyone still experiences this problem with `pg` 8 please let me know and I will reopen this.

However, in principle, it is Sequelize's fault to deep clone these things to begin with. I've opened #13168 to track this.

**Comment by jainabhishek14** [comment]
@papb Issue reappeared in v8.7.3

**Comment by RahmatAliMalik5** [comment]
I am still experiencing this issue with `pg` ^8.7.3. I have tried to delete `native` property by using the `delete (<any>pg).native` and `delete pg.native`. Also I have set `logging: false`. I am using `sequelize` in `nestjs` with `angular ssr`. Also using `native:false` The details are as follows:

```
      const sequelize = new Sequelize({
        database: 'vdp',
        dialect: 'postgres',
        native: false,
        username: 'postgres',
        password: 'root',
        host: 'localhost',
        port: 5432,
        dialectModule: pg,
        define: {
          timestamps: false,
        },
        logging: false,
      });
```


Package.json:

```

  "dependencies": {
    "@angular/animations": "^14.0.0",
    "@angular/cdk": "^14.1.0",
    "@angular/common": "^14.0.0",
    "@angular/compiler": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "@angular/material": "^14.0.3",
    "@angular/platform-browser": "^14.0.0",
    "@angular/platform-browser-dynamic": "^14.0.0",
    "@angular/platform-server": "^14.0.0",
    "@angular/router": "^14.0.0",
    "@nestjs/cli": "^8.2.8",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/ng-universal": "^6.1.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/sequelize": "^8.0.1",
    "@nguniversal/express-engine": "^14.0.0",
    "body-parser": "^1.20.0",
    "bootstrap": "^5.1.3",
    "chart.js": "^3.8.0",
    "chartjs-plugin-datalabels": "^2.0.0",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "compression": "^1.7.4",
    "express": "^4.15.2",
    "helmet": "^5.1.0",
    "mysql2": "^2.3.3",
    "ngx-papaparse": "^5.1.0",
    "ngx-scrollbar": "^10.0.0",
    "pg": "^8.7.3",
    "pg-hstore": "^2.3.4",
    "primeicons": "^5.0.0",
    "primeng": "^14.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~7.5.0",
    "sequelize": "^6.21.1",
    "sequelize-typescript": "^2.1.3",
    "tslib": "^2.3.0",
    "xlsx": "https://cdn.sheetjs.com/xlsx-0.18.9/xlsx-0.18.9.tgz",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.0.2",
    "@angular/cli": "~14.0.2",
    "@angular/compiler-cli": "^14.0.0",
    "@nguniversal/builders": "^14.0.0",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~4.0.0",
    "@types/sequelize": "^4.28.13",
    "jasmine-core": "~4.1.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.7.2"
  }
```


I have read all the thread and tried everything commented by the community. Nothing worked for me.
