### ISSUE TITLE
Update from 3.8.0 -> 3.18.0, JSON/JSONB, Error: val.replace undefined in sql-string.js

### ISSUE THREAD

**Issue by bkniffler** [sequelize/sequelize#5288]
Hey, 
I'm having an error [val.replace is not a function] in sql-string.js after updating sequelize 3.8.0 to 3.18.0. It only occurs if val is of type object, so it seems to dislike JSON/JSONB postgres column types.

I noticed https://github.com/sequelize/sequelize/commit/4f74575afecdf5517ecc64a2f79573030ef48d37 removed
```javascript
if (typeof val === 'object' && val !== null) {		
     if (stringifyObjects) {		
       val = val.toString();		
     } else {		
       return SqlString.objectToValues(val, timeZone);		
    }		
}		
```
Why was this condition removed?

**Comment by janmeier** [comment]
JSON data should be stringified by the JSON datatype instead https://github.com/sequelize/sequelize/blob/master/lib/data-types.js#L504-L520

Can you show a test case?

**Comment by bkniffler** [comment]
I failed to replicate the issue in an isolated environment and, now, also in my root project. After some research I suspect that it might be the result of conflicting sequelize versions in my project its dependencies, as one had installed a different sequelize version.
