### ISSUE TITLE
Property 'options' does not exist on type 'Sequelize'.

### ISSUE THREAD

**Issue by pgraham** [sequelize/sequelize#11497]
## Issue Description

Typescript error attempting to access `options` property of sequlize instance after upgrading to v5 and removing @types/sequelize from dependencies.

### What are you doing?

```js
const { Sequelize } = require('sequelize');
const sequelize = new Sequelize(...);

const logger = { log: (msg: string): void => { console.log(msg); } };

logger.log(`Logging database host: ${sequelize.options.host}`);
```

### What do you expect to happen?

Code should continue to compile.

### What is actually happening?

Typescript compiler error:
```
Property 'options' does not exist on type 'Sequelize'.
```

### Environment

- Sequelize version: 5.19.2
- Node.js version: 12
- Operating System: MacOS
- If TypeScript related: TypeScript version: 3.6.3

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
You can use `config` https://github.com/sequelize/sequelize/blob/master/types/lib/sequelize.d.ts#L782

**Comment by pgraham** [comment]
@sushantdhiman This works for the compilation. Does `sequelize.config` have the same runtime value as `sequelize.options`?

**Comment by ephys** [comment]
Fixed in v7 by https://github.com/sequelize/sequelize/pull/13922
