### PR TITLE
fix(types): expose legacy "types" folder in export alias

### PR DESCRIPTION
**Pull request by anderson-arlen**
## Description Of Problem

Imports of things like 'sequelize/types/hooks' (which is used by sequelize-typescript) is broken when using Typescript's "nodenext" or "node16" module resolution strategies. One could update the imports to 'sequelize/lib/hooks', but doing so breaks the default Typescript module resolution. So projects like sequelize-typescript can't easily make that change.

**Currently anyone using the newer module resolution strategies along with sequelize-typescript have no upgrade path to a version of sequelize without the vulnerability mentioned in #14519** 

## Description Of Change

This is a different approach to #14719.

Instead of adding hooks to the exports in index.d.ts, we can just add a  "/types/" alias to the exports in package.json. Doing so allows imports of 'sequelize/types/hooks' to properly resolve using both older and newer Typescript module resolution strategies. In essence, importing /types/* will work as it always has regardless of module resolution strategy.

### CODE REVIEW

**Comment by fzn0x** [comment]
Will the typings conflict?

**Review by ephys — APPROVED** [review]
I've tested this against a few configurations and it works, no conflicts, thank you :)

**Comment by cage1618** [comment]
Cannot find module './data-types' after update to 6.25.1 😭

**Comment by fzn0x** [comment]
> Cannot find module './data-types' after update to 6.25.1 😭 @ephys

Hi, just in case someone looking up about this types issue, this is already fixed by ephys :), refer to latest v6, thank you!
