### PR TITLE
Add missing runtime dep: pg-hstore

### PR DESCRIPTION
**Pull request by neophob**
Hey

I found a little bug, after I upgraded from sequelize 2.0.0-rc3 to 2.0.0-rc7. The postgres hstore.js file require the pg-hstore module - which is not defined in the package.json file, here's a sample error:
```
>> Mocha exploded!
>> Error: The dialect postgres is not supported. (Error: Cannot find module 'pg-hstore')
>>     at new module.exports.Sequelize (/var/lib/jenkins/XXX/node_modules/sequelize/lib/sequelize.js:191:13)
```

### CODE REVIEW

**Comment by mickhansen** [comment]
It was removed since it's a PG requirement only, you should install it as user.
http://sequelize.readthedocs.org/en/latest/docs/getting-started/

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/pull/2889
